//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace In_Struct
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrukcija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instrukcija()
        {
            this.Racuns = new HashSet<Racun>();
            this.Termins = new HashSet<Termin>();
        }
    
        public int instrukcija_ID { get; set; }
        public string predmet { get; set; }
        public int cijena { get; set; }
        public int trajanje { get; set; }
        public string mjesto { get; set; }
        public string adresa { get; set; }
        public int instruktor_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Racun> Racuns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Termin> Termins { get; set; }
        public virtual Korisnik Korisnik { get; set; }
    }
}
