//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace In_Struct
{
    using System;
    using System.Collections.Generic;
    
    public partial class pripada
    {
        public int termin_ID { get; set; }
        public int korisnik_ID { get; set; }
        public bool racunIzdan { get; set; }
        public int pripada_ID { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Termin Termin { get; set; }
    }
}
