//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace In_Struct
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racun
    {
        public int racun_ID { get; set; }
        public int ucenik_ID { get; set; }
        public int instruktor_ID { get; set; }
        public int instrukcija_ID { get; set; }
        public int termin_ID { get; set; }
    
        public virtual Instrukcija Instrukcija { get; set; }
        public virtual Korisnik Korisnik { get; set; }
        public virtual Korisnik Korisnik1 { get; set; }
        public virtual Termin Termin { get; set; }
    }
}
