//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace In_Struct
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recenzija
    {
        public int recenzija_ID { get; set; }
        public int Ocjena { get; set; }
        public string Komentar { get; set; }
        public int ucenik_ID { get; set; }
        public int instruktor_ID { get; set; }
        public int Tip_recenzije_ID { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Korisnik Korisnik1 { get; set; }
        public virtual Tip_recenzije Tip_recenzije { get; set; }
    }
}
