//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace In_Struct
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Termin()
        {
            this.Racuns = new HashSet<Racun>();
            this.pripadas = new HashSet<pripada>();
        }
    
        public int termin_ID { get; set; }
        public int broj_mjesta { get; set; }
        public System.DateTime vrijeme { get; set; }
        public int instrukcija_ID { get; set; }
    
        public virtual Instrukcija Instrukcija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Racun> Racuns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pripada> pripadas { get; set; }
    }
}
